
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1265
     no. of nonzeroes in lower triangle of a =           12227
     no. of nonzeroes in the factor l        =           31146
     ratio of nonzeroes in factor (min/max)  =          0.6988
     number of super nodes                   =              96
     maximum order of a front matrix         =              42
     maximum size of a front matrix          =             903
     maximum size of a front trapezoid       =             903
     no. of floating point ops for factor    =      4.5424D+05
     no. of floating point ops for solve     =      2.2371D+05
     ratio of flops for factor (min/max)     =          0.6741
     ratio of allocated memory (max/min)     =          1.1318
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000068
     time (cpu & wall) for ordering          =        0.000000        0.001615
     time (cpu & wall) for other matrix prep =        0.000000        0.000940
     time (cpu & wall) for value input       =        0.000000        0.000071
     time (cpu & wall) for matrix distrib.   =        0.031250        0.027574
     time (cpu & wall) for numeric factor    =        0.015625        0.013196
     computational rate (gflops) for factor  =        0.029071        0.034423

     no input or output performed

  Solver Memory allocated on core    0       =        0.567 MB
  Solver Memory allocated on core    1       =        0.531 MB
  Solver Memory allocated on core    2       =        0.503 MB
  Solver Memory allocated on core    3       =        0.501 MB
  Total Solver Memory allocated by all cores =        2.102 MB

