
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1985
     no. of nonzeroes in lower triangle of a =           19355
     no. of nonzeroes in the factor l        =           49532
     ratio of nonzeroes in factor (min/max)  =          0.9392
     number of super nodes                   =             150
     maximum order of a front matrix         =              54
     maximum size of a front matrix          =            1485
     maximum size of a front trapezoid       =            1485
     no. of floating point ops for factor    =      8.3390D+05
     no. of floating point ops for solve     =      2.8052D+05
     ratio of flops for factor (min/max)     =          0.7817
     ratio of allocated memory (max/min)     =          1.0928
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000056
     time (cpu & wall) for ordering          =        0.000000        0.001083
     time (cpu & wall) for other matrix prep =        0.000000        0.001566
     time (cpu & wall) for value input       =        0.000000        0.000084
     time (cpu & wall) for matrix distrib.   =        0.031250        0.031499
     time (cpu & wall) for numeric factor    =        0.015625        0.017786
     computational rate (gflops) for factor  =        0.053370        0.046885

     no input or output performed

  Solver Memory allocated on core    0       =        0.705 MB
  Solver Memory allocated on core    1       =        0.659 MB
  Solver Memory allocated on core    2       =        0.654 MB
  Solver Memory allocated on core    3       =        0.645 MB
  Total Solver Memory allocated by all cores =        2.663 MB

