
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            3576
     no. of nonzeroes in lower triangle of a =           34305
     no. of nonzeroes in the factor l        =           90683
     ratio of nonzeroes in factor (min/max)  =          0.9066
     number of super nodes                   =             251
     maximum order of a front matrix         =              42
     maximum size of a front matrix          =             903
     maximum size of a front trapezoid       =             732
     no. of floating point ops for factor    =      1.4552D+06
     no. of floating point ops for solve     =      3.9906D+05
     ratio of flops for factor (min/max)     =          0.8836
     ratio of allocated memory (max/min)     =          1.0750
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000054
     time (cpu & wall) for ordering          =        0.000000        0.001487
     time (cpu & wall) for other matrix prep =        0.000000        0.000953
     time (cpu & wall) for value input       =        0.000000        0.000082
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000911

     no input or output performed

  Solver Memory allocated on core    0       =        1.026 MB
  Solver Memory allocated on core    1       =        0.986 MB
  Solver Memory allocated on core    2       =        0.955 MB
  Solver Memory allocated on core    3       =        0.962 MB
  Total Solver Memory allocated by all cores =        3.929 MB

