
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10140
     no. of nonzeroes in lower triangle of a =           97941
     no. of nonzeroes in the factor l        =          278775
     ratio of nonzeroes in factor (min/max)  =          0.8998
     number of super nodes                   =             686
     maximum order of a front matrix         =             102
     maximum size of a front matrix          =            5253
     maximum size of a front trapezoid       =            2667
     no. of floating point ops for factor    =      5.6011D+06
     no. of floating point ops for solve     =      9.6402D+05
     ratio of flops for factor (min/max)     =          0.8363
     ratio of allocated memory (max/min)     =          1.0534
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000349
     time (cpu & wall) for ordering          =        0.000000        0.003399
     time (cpu & wall) for other matrix prep =        0.015625        0.001859
     time (cpu & wall) for value input       =        0.000000        0.000610
     time (cpu & wall) for matrix distrib.   =        0.000000        0.002600

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         28833.        0. MB
                95-   1         32768.        0. MB         29597.        0. MB
                95-   2         32768.        0. MB         28788.        0. MB
                95-   3         32768.        0. MB         29158.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB        116376.        1. MB


  Solver Memory allocated on core    0       =        2.581 MB
  Solver Memory allocated on core    1       =        2.517 MB
  Solver Memory allocated on core    2       =        2.535 MB
  Solver Memory allocated on core    3       =        2.450 MB
  Total Solver Memory allocated by all cores =       10.083 MB

