
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            2652
     no. of nonzeroes in lower triangle of a =           25401
     no. of nonzeroes in the factor l        =           67417
     ratio of nonzeroes in factor (min/max)  =          0.8530
     number of super nodes                   =             191
     maximum order of a front matrix         =              48
     maximum size of a front matrix          =            1176
     maximum size of a front trapezoid       =             510
     no. of floating point ops for factor    =      1.0705D+06
     no. of floating point ops for solve     =      3.3078D+05
     ratio of flops for factor (min/max)     =          0.8037
     ratio of allocated memory (max/min)     =          1.0579
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000047
     time (cpu & wall) for ordering          =        0.000000        0.001405
     time (cpu & wall) for other matrix prep =        0.000000        0.001235
     time (cpu & wall) for value input       =        0.000000        0.000072
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000808
     time (cpu & wall) for numeric factor    =        0.015625        0.002423
     computational rate (gflops) for factor  =        0.068511        0.441854

     no input or output performed

  Solver Memory allocated on core    0       =        0.819 MB
  Solver Memory allocated on core    1       =        0.803 MB
  Solver Memory allocated on core    2       =        0.774 MB
  Solver Memory allocated on core    3       =        0.783 MB
  Total Solver Memory allocated by all cores =        3.180 MB

