



  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            2652
     no. of nonzeroes in lower triangle of a =           25401
     no. of nonzeroes in the factor l        =           67571
     ratio of nonzeroes in factor (min/max)  =          0.8671
     number of super nodes                   =             189
     maximum order of a front matrix         =              48
     maximum size of a front matrix          =            1176
     maximum size of a front trapezoid       =             732
     no. of floating point ops for factor    =      1.0872D+06
     no. of floating point ops for solve     =      5.2467D+05
     ratio of flops for factor (min/max)     =          0.8216
     ratio of allocated memory (max/min)     =          1.0408
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     no input or output performed

  Solver Memory allocated on core    0       =        0.690 MB
  Solver Memory allocated on core    1       =        0.690 MB
  Solver Memory allocated on core    2       =        0.663 MB
  Solver Memory allocated on core    3       =        0.683 MB
  Total Solver Memory allocated by all cores =        2.726 MB

