
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            3087
     no. of nonzeroes in lower triangle of a =           45012
     no. of nonzeroes in the factor l        =           80508
     ratio of nonzeroes in factor (min/max)  =          0.8272
     number of super nodes                   =             258
     maximum order of a front matrix         =              42
     maximum size of a front matrix          =             903
     maximum size of a front trapezoid       =             672
     no. of floating point ops for factor    =      1.1730D+06
     no. of floating point ops for solve     =      2.2080D+05
     ratio of flops for factor (min/max)     =          0.8316
     ratio of allocated memory (max/min)     =          1.1038
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000134
     time (cpu & wall) for ordering          =        0.000000        0.003249
     time (cpu & wall) for other matrix prep =        0.015625        0.002210
     time (cpu & wall) for value input       =        0.000000        0.000211
     time (cpu & wall) for matrix distrib.   =        0.000000        0.003020

     no input or output performed

  Solver Memory allocated on core    0       =        1.134 MB
  Solver Memory allocated on core    1       =        1.161 MB
  Solver Memory allocated on core    2       =        1.059 MB
  Solver Memory allocated on core    3       =        1.052 MB
  Total Solver Memory allocated by all cores =        4.406 MB

